name: ETH Snapshot → Repo

on:
  workflow_dispatch: {}                # allow manual "Run workflow"
  schedule:
    - cron: "32 * * * *"               # run at minute :32 every hour (UTC); we’ll filter to Chicago 01/07/13/19 below

permissions:
  contents: write                      # let the workflow push commits

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Compute Chicago time
        id: tz
        run: |
          echo "NOW=$(TZ=America/Chicago date -Iseconds)" >> $GITHUB_OUTPUT
          echo "HOUR=$(TZ=America/Chicago date +%H)" >> $GITHUB_OUTPUT

      # Only proceed at 01, 07, 13, 19 in America/Chicago
      - name: Fetch snapshot
        if: contains('01,07,13,19', steps.tz.outputs.HOUR)
        run: |
          mkdir -p data
          curl -sS https://ethusd-anchor.vercel.app/api/eth-snapshot -o data/latest_eth_snapshot.json

          # init CSV header on first run
          if [ ! -f data/anchor_log.csv ]; then
            echo "ts_ct,anchor,used,age_sec,cross_price,disc_level,disc_diff_pct" > data/anchor_log.csv
          fi

          # append one row
          jq -r --arg ts "${{ steps.tz.outputs.NOW }}" '
            [$ts,
             .anchor.price,
             .anchor.used,
             (.anchor.anchor_age_seconds // ""),
             (.cross_check.price // ""),
             (.cross_check.discrepancy.level // ""),
             (.cross_check.discrepancy.diff_pct // "")]
          | @csv' data/latest_eth_snapshot.json >> data/anchor_log.csv

      - name: Commit & push (if ran this hour)
        if: contains('01,07,13,19', steps.tz.outputs.HOUR)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest_eth_snapshot.json data/anchor_log.csv
          git commit -m "snapshot: ${{ steps.tz.outputs.NOW }} CT" || exit 0
          git push
